# Generated by Django 4.2.1 on 2024-05-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="receipts/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="receipts/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "converted_csv",
                    models.FileField(
                        blank=True, null=True, upload_to="receipts/converted_csv/"
                    ),
                ),
                (
                    "status",
                    models.CharField(default="Failed To convert", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConvertedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="receipts/converted_csv/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="converter.pdffile",
                    ),
                ),
            ],
        ),
    ]
